@rootURL = http://localhost:8000
@apiEP = {{rootURL}}/api/v1
@userAPI = {{apiEP}}/users
@bookAPI = {{apiEP}}/books
@reviewAPI = {{apiEP}}/reviews



### Check teh server status
GET {{rootURL}}

###===== user api
### Get user  
GET {{userAPI}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MTk4NzU4MDgsImV4cCI6MTcxOTg3NjcwOH0.lGhCFzpTjmhhkkglUHdfsZimWU6M-CJHCl_2Ulp7D98

### login user 
POST {{userAPI}}/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "as"
}
  

# ======== Book
### Get all books for the admin 
GET {{bookAPI}}/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MTY4NTE1NjksImV4cCI6MTcxNjg1MTYyOX0.iJPaoDTwqcY7udFwkvLQLlTCqRjve1430CzduQEUqes



### Get all public books for the user 
GET {{bookAPI}}/



###===== REviews api
### Get review  
GET {{reviewAPI}}